volumes:
  redis-data:
  sqlite-data:

services:
  redis-infra:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  bull:
    image: venatum/bull-board:latest
    ports:
      - "4000:3000"
    environment:
      - REDIS_HOST=redis-infra
      - REDIS_PORT=6379
    depends_on:
      redis-infra:
        condition: service_healthy
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: dev
    environment:
      - PORT=3000
      - REDIS_HOST=redis-infra
      - REDIS_PORT=6379
      - DATABASE_URL=/monorepo/data/test.db
    ports:
      - "3000:3000"
    depends_on:
      redis-infra:
        condition: service_healthy
    volumes:
      - .:/monorepo
      - /monorepo/node_modules
      - /monorepo/apps/server/node_modules
      - sqlite-data:/monorepo/data
  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: dev
    environment:
      - NODE_OPTIONS=--max-old-space-size=5120
      - REDIS_HOST=redis-infra
      - REDIS_PORT=6379
      - DATABASE_URL=/app/data/test.db
    depends_on:
      redis-infra:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/worker/node_modules
      - sqlite-data:/app/data
